services:
  labenv:
    image: sh3b0/labenv:stable
    container_name: labenv
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8080:8080"
    volumes:
      - ./workspace:/home/ubuntu
      - ./lab1:/app/workshop
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lab_net

networks:
  lab_net:
    name: lab_net
